### PR TITLE
Update to support latest subscription-transport-ws (0.8.2)

### PR DESCRIPTION
**Pull request by DxCx**

### CODE REVIEW

**Comment by theikkila** [comment]
Any updates on this?

**Comment by DxCx** [comment]
@Urigo ??

**Comment by tlvenn** [comment]
@Urigo can we please get this merged ? Thanks in advance

**Comment by tlvenn** [comment]
@DxCx you might want to update the dependencies on `graphql` and `subscription-transport-ws` before this get merged.

**Comment by DxCx** [comment]
im not sure when uri will merge, versions might progress even further..

**Comment by tlvenn** [comment]
Ya I hear you, I was kinda hopeful that somehow @Urigo would resurface this time around. He tweeted last week so at least he seems well.

**Comment by tlvenn** [comment]
@stubailo is there anything you can do from an org perspective to reach out to @Urigo and resolve the situation plz ?

**Comment by DxCx** [comment]
well, its here for almost a year, not gonna happen i guess..

**Pull request closed without merging**
